#include<stdio.h>
#include<stdlib.h>
#include<time.h>
#include<stdbool.h>

#define max_length  11//maximum length of the genrated string
#define min_length  5 //minimum length of the genrated string 

#define alpha_max_ascii 88//ascii value of X
#define alpha_min_ascii 65//ascii value of A

#define salpha_max_ascii 120//ascii value of x 
#define salpha_min_ascii 97//ascii value of a

#define digit_max_ascii 57//ascii value of 9
#define digit_min_ascii 48//ascii value of 0
//function decleration
char generate_random_alphanum_char();
void generateAlphanumericPalindrome(char*, int);
int fact(int);
char generate_random_alphanum_char() //function to genrate the random alpha numeric character 
{
    int chance;// random variable to determine wether small or capital alphabet or number char is going to be generated
    char palindrome;// variable to store generated character

    chance = rand() % 3;//0,1 or 2 is generated randomly

        if (chance == 0)//chance 0 will give a digit ascii
        palindrome = rand() % ((digit_max_ascii - digit_min_ascii)+1) + digit_min_ascii;

         if (chance == 1)//chance 1 will give a capital alphabet letter
        palindrome = rand() % ((alpha_max_ascii - alpha_min_ascii)+1) + alpha_min_ascii;

        if(chance == 2)//chance 2 will give a small alphabet letter
        palindrome = rand() % ((salpha_max_ascii - salpha_min_ascii)+1) + salpha_min_ascii;

        return palindrome;//palindrome variable will return the randomly generated character
    
}


void generateAlphanumericPalindrome(char *str, int length) // function to generate a pindrome string
{
    
    // Generating half of the palindrome
    for (size_t i = 0; i < (length+1) / 2; i++)
    {
        str[i] = generate_random_alphanum_char ();//function rndomly generated alpha numeric character is called
    }

    // Mirroring it to create a palindrome
    for (size_t i = 0; i < length; i++)
    {
        str[i] = str[length - i - 1];//the same string is repated in reverse order
    }

    str[length] = '\0';// null character to end the string
}


int fact(int n)//function to check the no. of palindromes genrated
{
    n = n/2;

    if (n>=1)
        return n*fact(n-1);
    else
        return 1;

}
//main function
int main() {

    int length;//variable length will detrmine the length of the string
    srand(time(NULL)); // function that the random number generator with the current time

    length = rand() % ((max_length - min_length) + 1) + min_length;//length will be determined randomly between 5 to 11
    char palindrome[length + 1];//array to store palindrome characters

    
    generateAlphanumericPalindrome(palindrome, max_length);//function to generate pallindrome is called

    printf("Generated Alphanumeric Palindrome: %s\n", palindrome);//palindrome is printed

    int combinations = fact(length);//to determine combinations which generate palindrome

    printf("The total no. of Palindromes can be generated by the string is %d",combinations);//number of palindrome printed
    return 0;
}







